In [30]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot  as plt
%matplotlib inline

#import image_audio as ia
#from checkarr import array_hash, check_hash

In [6]:
x = np.array([1.0, 2.0, 3.0, 4.0]) #create an array from a list

print(x) # print the values in the array
print(x.dtype) # print datatype of values in the array
print(x.shape) #print hte shape (dimensions) of the array

[1. 2. 3. 4.]
float64
(4,)


In [8]:
x = np.zeros((3,3)) #a 3 X 3 matrix of all zeros
print("X\n", x)

X
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
y = np.ones(13) # a 13 element 1 D vector of all ones
print("Y\n", y)

Y
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
scalar = 7
m = np.full((3,3), scalar) #create a matrix or array of specified shape and filled with a value of a scalar
print("m\n",m)

m
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [16]:
np.zeros_like(m) #create a matrix or array similar to speecifed value with all zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
z = np.full((2,3,4), 9.1) #create a 2 x 3 x 4 with all elements 9.1
print ("z\n", z)

z
 [[[9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]]

 [[9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]]]


In [27]:
u = np.random.uniform(-1, 1, (4,8)) #create a 8 column, 4 rows array
                                    #with numbers randomly uniform distributed in the range [-1,1) (uniform)
print("u\n", u)

u
 [[ 0.55256761 -0.64449978  0.80839925  0.33687032  0.73387438 -0.17241049
  -0.37363476 -0.28660245]
 [-0.68383104  0.58395852  0.63281174  0.03973379  0.67140555 -0.70417685
  -0.5892951   0.67748613]
 [-0.05877435  0.53171252  0.77737566 -0.18336773 -0.21520524  0.3673652
   0.55178911 -0.4285236 ]
 [ 0.99183084 -0.99793358  0.91048426  0.23026003  0.31911704 -0.52748743
   0.30175714  0.71757402]]


In [26]:
r = np.random.randint(-1, 1, (4,8)) #create a 8 column, 4 rows array
                                    #with numbers randomly distributed in the range [-1,1) (integers only)
print("r\n", r)

r
 [[-1 -1  0  0  0 -1 -1  0]
 [-1 -1 -1  0 -1 -1  0 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1  0 -1]]


In [28]:
n = np.random.normal(-1, 1, (4,8)) #create a 8 column, 4 rows array
                                    #with numbers randomly normally distributed in the range [-1,1)
print("n\n", n)

n
 [[-0.89282934  0.01693095 -2.08269497  0.94223025 -2.83422727 -2.05478482
   0.06640216 -0.03837   ]
 [-0.68313432 -0.01435163 -0.16215401 -0.82180618 -2.03921461 -2.8579159
  -2.05315447  0.28440306]
 [-0.55572443 -1.29255851 -0.82936453  0.49490241  0.4232886   0.57129997
   0.10009966 -3.0959698 ]
 [-2.96499333  0.39527552 -0.98217388  0.44757301 -2.13111179  0.74176871
  -1.43794536 -1.3545049 ]]
