# Lab1

### Create some arrays

In [3]:
x = np.array([1.0, 2.0, 3.0, 4.0]) #create an array from a list

print(x) # print the values in the array
print(x.dtype) # print datatype of values in the array
print(x.shape) #print hte shape (dimensions) of the array

[1. 2. 3. 4.]
float64
(4,)


In [4]:
x = np.zeros((3,3)) #a 3 X 3 matrix of all zeros
print("X\n", x)

X
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
y = np.ones(13) # a 13 element 1 D vector of all ones
print("Y\n", y)

Y
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
scalar = 7
m = np.full((3,3), scalar) #create a matrix or array of specified shape and filled with a value of a scalar
print("m\n",m)

m
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
np.zeros_like(m) #create a matrix or array similar to speecifed value with all zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
z = np.full((2,3,4), 9.1) #create a 2 x 3 x 4 with all elements 9.1
print ("z\n", z)

z
 [[[9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]]

 [[9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]
  [9.1 9.1 9.1 9.1]]]


In [9]:
u = np.random.uniform(-1, 1, (4,8)) #create a 8 column, 4 rows array
                                    #with numbers randomly uniform distributed in the range [-1,1) (uniform)
print("u\n", u)

u
 [[-0.17882095  0.11819598  0.24699511 -0.63225903  0.78077904  0.53323504
  -0.41015522  0.88460154]
 [ 0.11915712 -0.51537732  0.90196973  0.28621471 -0.26583027 -0.72154382
   0.71812173 -0.52950245]
 [-0.49845429  0.765489    0.23665966  0.78967115 -0.09466406  0.37910435
  -0.15728868  0.48441858]
 [ 0.22601063  0.81911189 -0.36930609 -0.49681768  0.59970438 -0.89354992
   0.01879212  0.88520653]]


In [10]:
r = np.random.randint(-1, 1, (4,8)) #create a 8 column, 4 rows array
                                    #with numbers randomly distributed in the range [-1,1) (integers only)
print("r\n", r)

r
 [[-1 -1 -1  0  0 -1 -1  0]
 [ 0  0 -1 -1 -1 -1 -1 -1]
 [ 0  0  0 -1  0 -1 -1 -1]
 [ 0  0  0 -1  0  0  0 -1]]


In [11]:
n = np.random.normal(-1, 1, (4,8)) #create a 8 column, 4 rows array
                                    #with numbers randomly normally distributed in the range [-1,1)
print("n\n", n)

n
 [[-1.73461142 -2.20960562 -1.55552724 -2.93566798 -1.15699595 -0.39188744
  -0.76112502  0.45155941]
 [-2.95638252 -0.94612865 -0.63218794 -1.3380812  -1.23923781 -0.77921214
  -1.02967553 -1.25262444]
 [ 0.25004625 -2.21650806 -1.55655822 -0.92780037 -1.77484952 -0.04607343
  -1.65657077  0.60415138]
 [-2.13823918 -1.7482697  -0.01057935 -2.08677412 -0.92487373 -0.1109848
  -1.93626126 -0.02178016]]


In [12]:
# an array with 10 elemtns from 0-9
q = np.arange(9)
print('q\n', q)

q
 [0 1 2 3 4 5 6 7 8]


### The task

In [13]:
#load the snails data as a Numpy array called snails
#species(binary) exposure(weeks)  humidaty(%) temperture(deg. C) n_deaths  n_snails
snails = np.loadtxt("Data/snails.txt")
print("snails\n", snails)

snails
 [[ 0.   1.  60.  10.   0.  20. ]
 [ 0.   1.  60.  15.   0.  20. ]
 [ 0.   1.  60.  20.   0.  20. ]
 [ 0.   1.  65.8 10.   0.  20. ]
 [ 0.   1.  65.8 15.   0.  20. ]
 [ 0.   1.  65.8 20.   0.  20. ]
 [ 0.   1.  70.5 10.   0.  20. ]
 [ 0.   1.  70.5 15.   0.  20. ]
 [ 0.   1.  70.5 20.   0.  20. ]
 [ 0.   1.  75.8 10.   0.  20. ]
 [ 0.   1.  75.8 15.   0.  20. ]
 [ 0.   1.  75.8 20.   0.  20. ]
 [ 0.   2.  60.  10.   0.  20. ]
 [ 0.   2.  60.  15.   1.  20. ]
 [ 0.   2.  60.  20.   1.  20. ]
 [ 0.   2.  65.8 10.   0.  20. ]
 [ 0.   2.  65.8 15.   1.  20. ]
 [ 0.   2.  65.8 20.   0.  20. ]
 [ 0.   2.  70.5 10.   0.  20. ]
 [ 0.   2.  70.5 15.   0.  20. ]
 [ 0.   2.  70.5 20.   0.  20. ]
 [ 0.   2.  75.8 10.   0.  20. ]
 [ 0.   2.  75.8 15.   0.  20. ]
 [ 0.   2.  75.8 20.   0.  20. ]
 [ 0.   3.  60.  10.   1.  20. ]
 [ 0.   3.  60.  15.   4.  20. ]
 [ 0.   3.  60.  20.   5.  20. ]
 [ 0.   3.  65.8 10.   0.  20. ]
 [ 0.   3.  65.8 15.   2.  20. ]
 [ 0.   3.  65.8 20.   4.  20. ]
 [

In [29]:
snails.shape

(96, 6)

In [14]:
#humidity in the first entry in the table
hum_first = snails[1,2]
print("hum_first: ",hum_first)

hum_first:  60.0


In [15]:
#the temperature in the last entry in the table
temp_last = snails[-1,3]
print("temp_last: ", temp_last)

temp_last:  20.0


In [16]:
#the whole column of "week_exposure"
week_exp = snails[:,1]
print("week\n", week_exp)

week
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


In [17]:
#the 8th row of the observations
observations = snails[8,:]
print("8th week observations", observations)

8th week observations [ 0.   1.  70.5 20.   0.  20. ]


### Aggregate function

In [18]:
#total number of snails that died
total_deaths = np.sum(snails[:,4])
print("total deaths: ", total_deaths)

total deaths:  275.0


In [19]:
#total number of snails that survived the whole study
total_still_alive = np.sum(snails[:,-1]) - total_deaths
print("total_still_alive: ", total_still_alive)

total_still_alive:  1645.0


In [20]:
#mean tempretures in the whole study
mean_temp = np.mean(snails[:,3])
print("mean_temp: ", mean_temp)

mean_temp:  15.0


In [21]:
#hightest humidity
max_humidity = np.max(snails[:,2])
print("max_humidity: ", max_humidity)

max_humidity:  75.8


In [22]:
#mean of the ratio of snail deaths to snails in the study
average_death_rate = np.mean(snails[:,4] / snails[:, -1])
print("avergae_death_rate: ", average_death_rate)

avergae_death_rate:  0.14322916666666666


In [23]:
#the total amount of snails effort that went into the study (the number of snails times number of weeks)
snail_weeks = np.sum(snails[:,5] * snails[:,1])
print("snail_weeks: ", snail_weeks)

snail_weeks:  4800.0


### Boolean indexing

In [26]:
species_0 = snails[snails[:, 0] == 0]
species_1 = snails[snails[:, 0] == 1]

print("species 0\n", species_0)
print("species 1\n", species_1)

species 0
 [[ 0.   1.  60.  10.   0.  20. ]
 [ 0.   1.  60.  15.   0.  20. ]
 [ 0.   1.  60.  20.   0.  20. ]
 [ 0.   1.  65.8 10.   0.  20. ]
 [ 0.   1.  65.8 15.   0.  20. ]
 [ 0.   1.  65.8 20.   0.  20. ]
 [ 0.   1.  70.5 10.   0.  20. ]
 [ 0.   1.  70.5 15.   0.  20. ]
 [ 0.   1.  70.5 20.   0.  20. ]
 [ 0.   1.  75.8 10.   0.  20. ]
 [ 0.   1.  75.8 15.   0.  20. ]
 [ 0.   1.  75.8 20.   0.  20. ]
 [ 0.   2.  60.  10.   0.  20. ]
 [ 0.   2.  60.  15.   1.  20. ]
 [ 0.   2.  60.  20.   1.  20. ]
 [ 0.   2.  65.8 10.   0.  20. ]
 [ 0.   2.  65.8 15.   1.  20. ]
 [ 0.   2.  65.8 20.   0.  20. ]
 [ 0.   2.  70.5 10.   0.  20. ]
 [ 0.   2.  70.5 15.   0.  20. ]
 [ 0.   2.  70.5 20.   0.  20. ]
 [ 0.   2.  75.8 10.   0.  20. ]
 [ 0.   2.  75.8 15.   0.  20. ]
 [ 0.   2.  75.8 20.   0.  20. ]
 [ 0.   3.  60.  10.   1.  20. ]
 [ 0.   3.  60.  15.   4.  20. ]
 [ 0.   3.  60.  20.   5.  20. ]
 [ 0.   3.  65.8 10.   0.  20. ]
 [ 0.   3.  65.8 15.   2.  20. ]
 [ 0.   3.  65.8 20.   4.  20. ]

In [27]:
avg_death_rate_species_0 = np.mean(species_0[:,4] / species_0[:,5]) #the death rate in species 0
avg_death_rate_species_1 = np.mean(species_1[:,4] / species_1[:,5]) #the death rate in species 1

hardest_snail = 1 if avg_death_rate_species_0 > avg_death_rate_species_1 else 0
print("hardest_snials\n", hardest_snail)

hardest_snials
 0


In [30]:
# each temp. in the study in Fehrenhite. 0C=32F, 100C = 212F
deg_f = snails[:,3] * (212-32)/100 + 32
print(deg_f)

[50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68.
 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68.
 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68.
 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68.
 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68. 50. 59. 68.
 50. 59. 68. 50. 59. 68.]


In [33]:
#the mean of ll the columns as 1D vector
# axis specifies the direction of the mean 1 means by row 0 mean by column
mean_col = np.mean(snails, axis =0)
print(mean_col)

[ 0.5         2.5        68.025      15.          2.86458333 20.        ]


In [34]:
#deah rates sorted, smallest first
death_rate = snails[:,4] / snails[:,5]
death_rate_sorted = np.sort(death_rate)
print(death_rate_sorted)

[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.05
 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.1  0.1  0.1  0.1  0.1  0.1
 0.1  0.1  0.15 0.15 0.15 0.15 0.15 0.15 0.15 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.25 0.25 0.25 0.25 0.25 0.25 0.3  0.35 0.35 0.35 0.35 0.35
 0.35 0.35 0.45 0.45 0.5  0.55 0.55 0.6  0.6  0.6  0.7  0.8 ]


In [35]:
#death rate sorting 
death_rate_sorted_indexes = np.argsort(death_rate) #np.argsort() return the indexes of the sorted array
exposure_death_rate = snails[:, 1][death_rate_sorted_indexes]
print(exposure_death_rate) 

[1. 3. 1. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2.
 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 2. 2. 2. 3. 2. 3. 2. 2. 2.
 2. 2. 3. 3. 3. 2. 4. 2. 3. 3. 2. 3. 4. 4. 4. 4. 3. 4. 3. 3. 3. 3. 4. 4.
 4. 4. 3. 3. 4. 3. 3. 4. 4. 4. 4. 3. 4. 4. 4. 3. 4. 3. 3. 4. 4. 4. 4. 4.]


In [37]:
one_week_exposure = snails[snails[:,1] == 1]
least_deaths_index = np.argmin(one_week_exposure[:,4])
best_hum = snails[:,2][least_deaths_index]
best_temp = snails[:,3][least_deaths_index]

print("best hum", best_hum)
print("best temp", best_temp)

best hum 60.0
best temp 10.0
