# Numerical arrays in python (Numpy)

## Arrays

### What are they?
   * A Data type 
   * A container which can hold a fixed number of items of the same type 
   * Numerical arrays are arrays which all the elements are of numerical type (int or float)
   ![alt] [id] 
   [id]: ../imgs/arrays.png "Arrays"    

### Why do we need them?
  * **Abstraction**: extend operations we apply on single numbers to entire array of numbers
  *  __Efficiency__: compact and computationally effiecient

## Numpy
A fundemental package for large multi-dimensional arrays and matrices along with high-level mathematical functions to operate on these arrays.

In [2]:
import numpy as np

### Number types:
   * Integers
   * Floats
   * NaN

In [10]:
x = np.arange(0,10,1)
y = np.arange(0,5,0.2)
z = np.full(3, np.nan)

print("Integer array: \n", x, "\n")
print("Float array: \n", y, "\n")
print("Nan array: \n", z, "\n")

Integer array: 
 [0 1 2 3 4 5 6 7 8 9] 

Float array: 
 [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8] 

Nan array: 
 [nan nan nan] 



### Attributes:
  * **Shape**: the array shape is the array dimensions For example, 12X8
  * **Type**: the type of the elements: the dtype (e.g. float64)

In [16]:
x = np.array([[1,3,5,7,9],
              [2,4,6,8,10],
              [1.5,2.5,3.5,4.5,5.5]
             ])

print("shape", x.shape)
print("type", x.dtype)

shape (3, 5)
type float64


### ndarray
 **ndarray** (n-dimensional arrays) represent sequence with the following charcterised with:
 * Fixed, predefined size (shape)
 * Fixed, predefined type(all the elements of the same type)
 * They can only hold numbers
 * multidimensional
 * they are requred to be rectangular (a 2D array must have the same number of columns in each row)

### Indexing and types

**The shape of the array is descriped in this order:**
    * rows
    * columns
For example, A= [[0 0 0],
                 [0 0 0]]
            
A is 2X3 arrays means 2 row, 3 columns and (2*3 = 6 elements)
    
**We index from 0, so element[0,1] of an array means first row, second column**

## Creating arrays

### np.array

np.array() takes a sequence and converts it into an array

In [18]:
x = np.array([1,2,3,4,5])

print("x:\n", x, "\n")
print("type:\n", x.dtype)

x:
 [1 2 3 4 5] 

type:
 int64


This works also for multi-dimensiona arrays using nestes lists (list of lists)

In [20]:
y = np.array([[1., 2., 3.],
     [0., 0.5, 0.],
     [5., 0., 10.]])

print("y:\n", y, "\n")
print("Shape:\n", y.shape, "\n")
print("type:\n", y.dtype)

y:
 [[ 1.   2.   3. ]
 [ 0.   0.5  0. ]
 [ 5.   0.  10. ]] 

Shape:
 (3, 3) 

type:
 float64


In [22]:
#Ragged arrays  (not rectangular)
y = np.array([[1., 2., 3.],
     [0., 0.5],
     [5., 0., 10.,6., 10,5]])

print("y:\n", y, "\n")
print("Shape:\n", y.shape, "\n")
print("type:\n", y.dtype)

y:
 [list([1.0, 2.0, 3.0]) list([0.0, 0.5]) list([5.0, 0.0, 10.0, 6.0, 10, 5])] 

Shape:
 (3,) 

type:
 object


### creating blank arrays
blank arrays means arrays filled with the same value. This can be done using the following functions:
  * **np.zeros(shape)** creates an array with the defined shape full of zeros
  * **np.ones(shape)** works like np.zeros but full of 1s
  * **np.full(shape,a)** creates an array with the defined shape filled with the scalar value (a)
  * **np.zero_like(x)** creates an array with the same shape and type of array (x) but filled with 0s

In [24]:
x = np.zeros(5)
print (x)

[0. 0. 0. 0. 0.]


In [25]:
x = np.zeros((5,), dtype=int)
print(x)

[0 0 0 0 0]


In [26]:
x = np.zeros((2, 1))
print(x)

[[0.]
 [0.]]


In [16]:
x = np.ones(5)
print (x)

In [27]:
x = np.ones((5,), dtype=int)
print(x)

[1 1 1 1 1]


In [28]:
x = np.ones((2, 1))
print(x)

[[1.]
 [1.]]


In [29]:
s = 6
x = np.full((3,4), s)
print(x)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [32]:
z = np.zeros_like(x)
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### creating arrays (vectors) of increasing numbers

 * **np.arange(end)** return a vector starting from 0 to end-1
 * **np.arange(start, end)** returns a vector of numbers from start ... end-1
 * **np.arange(start, end, step)** return a vector of numbers from start to end-1 increasing by the step value


In [33]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [34]:
x = np.arange(0,5)
print(x)

[0 1 2 3 4]


In [35]:
x = np.arange(0, 5, 0.5)
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### Loadig and saving arrays
numpy arrays can be saved to and loaded from local text files 

* **np.savetxt(filename, array)** 
* **np.loadtxt(filename)**

In [45]:
np.savetxt('test_array.txt', x)

In [47]:
a = np.loadtxt('test_array.txt')
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## Indexing arrays


In [4]:
x = np.arange(10)
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(x[0])

0


In [5]:
print(x[2])

2


In [6]:
print(x[-2])

8


### Indexing multi-dimensional array

In [26]:
y = np.array([[1., 2., 3.],
     [0., 0.5, 0.],
     [5., 0., 10.]])

print(y)

[[ 1.   2.   3. ]
 [ 0.   0.5  0. ]
 [ 5.   0.  10. ]]


In [27]:
print(y[0])

[1. 2. 3.]


In [28]:
print(y[1,1])

0.5


## Slicing
Slice items starting from index 

In [33]:
a = np.arange(10) 
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
print (a[2:])

[2 3 4 5 6 7 8 9]


In [36]:
# slice items between indexes 
print (a[2:5])

[2 3 4]


In [37]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [38]:
# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


## Rearange

In [39]:
a = np.array([[10, 20, 30, 40, 50],
             [ 6,  7,  8,  9, 10]])

print(a)

[[10 20 30 40 50]
 [ 6  7  8  9 10]]


In [41]:
your_permutation = [0,4,1,3,2]
i = np.argsort(your_permutation)
print(i)

[0 2 4 3 1]


In [42]:
re_arranged_a = a[:,i]
print(re_arranged_a)

[[10 30 50 40 20]
 [ 6  8 10  9  7]]


In [43]:
a = np.arange(9, dtype = np.float_)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [45]:
rearranged_a = a.reshape(3,3) 
print(rearranged_a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


## Arithmatic operations

In [54]:
a = np.arange(0,6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [55]:
b = np.array([10,10,10]) 
print(b,'\n' )

[10 10 10] 



In [59]:
at = a.T
print(at)

[[0 3]
 [1 4]
 [2 5]]


In [56]:
print ('Add the two arrays:') 
print (np.add(a,b),'\n') 
  

print ('Subtract the two arrays:' )
print (np.subtract(a,b),'\n') 
 

print ('Multiply the two arrays:') 
print (np.multiply(a,b), '\n') 
   

print ('Divide the two arrays:') 
print (np.divide(a,b))

Add the two arrays:
[[10 11 12]
 [13 14 15]] 

Subtract the two arrays:
[[-10  -9  -8]
 [ -7  -6  -5]] 

Multiply the two arrays:
[[ 0 10 20]
 [30 40 50]] 

Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]]


In [69]:
x = np.arange(1,5).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [70]:
from numpy.linalg import inv

xi = inv(x)
print(xi)

[[-2.   1. ]
 [ 1.5 -0.5]]
